### ISSUE TITLE
Adding instances for MonoFunctor and MonoFoldable.

### ISSUE THREAD

**Issue by jship** [nikita-volkov/bit-array#3]
Any interest in instances of `MonoFunctor` and `MonoFoldable`?  This treats `BitArray` as a finite container of bools and opens up all of the `Functor` and `Foldable` functionality for the monomorphic  `BitArray`.

I have implemented this on a [branch in my fork](https://github.com/jship/bit-array/tree/mono_traversable).

Let me know if you'd like this incorporated in the repo and I'll open up a PR.

**Comment by nikita-volkov** [comment]
Those abstractions are experimental and their APIs aren't stable, so I'm afraid this has a high potential of becoming a maintenance head-ache.

**Comment by jship** [comment]
No problem.  I'll keep the branch in my fork in case it's something to explore when `mono-traversable` is more stable.
